# [[plugins]]
# repo = 'moll/vim-node'

[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
let g:dein#install_log_filename = '~/.neovim-dein-install.log'
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'w0rp/ale'
on_event = 'BufEnter'
if = 'has("nvim")'
hook_add = '''
source  ~/.config/nvim/plugins/ale.rc.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
"call airline#parts#define_function('ALE', 'ale#statusline#Count()')
"call airline#parts#define_condition('ALE', 'exists("*ale#statusline#Count()")')
"let g:airline_section_error = airline#section#create_right(['ALE'])
let g:airline#extensions#ale#enabled = 1

" let g:airline_powerline_fonts = 1

" " unicode symbols
let g:airline_symbols = {}
let g:airline_left_sep = 'Â»'
let g:airline_left_sep = 'â–¶'
let g:airline_right_sep = 'Â«'
let g:airline_right_sep = 'â—€'
let g:airline_symbols.crypt = 'ğŸ”’'
let g:airline_symbols.linenr = 'âŠ'
let g:airline_symbols.linenr = 'â¤'
let g:airline_symbols.linenr = 'Â¶'
let g:airline_symbols.maxlinenr = 'â˜°'
let g:airline_symbols.maxlinenr = ''
let g:airline_symbols.branch = 'â‡'
let g:airline_symbols.paste = 'Ï'
let g:airline_symbols.paste = 'Ã'
let g:airline_symbols.paste = 'âˆ¥'
let g:airline_symbols.spell = 'ê¨'
let g:airline_symbols.notexists = 'âˆ„'
let g:airline_symbols.whitespace = 'Î'

let g:airline_left_sep = 'î‚°'
let g:airline_left_alt_sep = 'î‚±'
let g:airline_right_sep = 'î‚²'
let g:airline_right_alt_sep = 'î‚³'
let g:airline_symbols.branch = 'î‚ '
let g:airline_symbols.readonly = 'î‚¢'
let g:airline_symbols.linenr = 'î‚¡'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  let g:airline_theme='hybrid'
'''

[[plugins]]
repo = 'w0ng/vim-hybrid'

# [[plugins]]
# repo = 'Yggdroot/indentLine'
# on_path = '.*'
# hook_add = '''
#   let g:indentLine_enabled = 1
#   let g:indentLine_fileTypeExclude = ['help', 'json']
#   let g:indentLine_concealcursor = 'c'
#   let g:indentLine_conceallevel=1
# '''

[[plugins]]
repo = 'romgrk/winteract.vim'

# [[plugins]]
# repo = 'ryanoasis/vim-devicons'

##################################################################
# syntax

[[plugins]] # js syntax
repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'kylef/apiblueprint.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
  let g:polyglot_disabled = ['javascript', 'elm']
  " vim-cpp-enhanced-highlight
  let g:cpp_class_scope_highlight = 1
'''
# polyglot includes these
# repo = 'cespare/vim-toml'
# repo = 'rust-lang/rust.vim'
# repo = 'leafgarland/typescript-vim'
# repo = 'octol/vim-cpp-enhanced-highlight'

[[plugins]]
repo = 'numirias/semshi'
on_ft = 'python'
# lazy = 0
hook_add = '''
" guifgã¯å¤‰æ›´ã—ã¦ã„ãªã„
function MyCustomHighlights()
  " hi semshiLocal           ctermfg=3 guifg=#ff875f " ?
  hi semshiGlobal          ctermfg=3 guifg=#ffaf00
  hi semshiImported        ctermfg=3 guifg=#ffaf00
  hi semshiParameter       ctermfg=12  guifg=#5fafff
  " hi semshiParameterUnused ctermfg=117 guifg=#87d7ff cterm=underline gui=underline
  " hi semshiFree            ctermfg=218 guifg=#ffafd7 " ?
  hi semshiBuiltin         ctermfg=13 guifg=#ff5fff
  hi semshiAttribute       ctermfg=14  guifg=#00ffaf
  " hi semshiSelf            ctermfg=249 guifg=#b2b2b2
  " hi semshiUnresolved      ctermfg=226 guifg=#ffff00 cterm=underline gui=underline
  hi semshiSelected        ctermfg=231 guifg=#ffffff ctermbg=52 guibg=#d7005f
endfunction
autocmd FileType python call MyCustomHighlights()
'''

[[plugins]]
repo = 'google/vim-jsonnet'
