[[plugins]]
repo = 'moll/vim-node'

[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
let g:dein#install_log_filename = '~/.neovim-dein-install.log'
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
call airline#parts#define_function('ALE', 'ALEGetStatusLine')
call airline#parts#define_condition('ALE', 'exists("*ALEGetStatusLine")')

let g:airline_section_error = airline#section#create_right(['ALE'])

let g:airline_powerline_fonts = 1

" unicode symbols
let g:airline_left_sep = 'Â»'
let g:airline_left_sep = 'â–¶'
let g:airline_right_sep = 'Â«'
let g:airline_right_sep = 'â—€'
let g:airline_symbols.crypt = 'ğŸ”’'
let g:airline_symbols.linenr = 'âŠ'
let g:airline_symbols.linenr = 'â¤'
let g:airline_symbols.linenr = 'Â¶'
let g:airline_symbols.maxlinenr = 'â˜°'
let g:airline_symbols.maxlinenr = ''
let g:airline_symbols.branch = 'â‡'
let g:airline_symbols.paste = 'Ï'
let g:airline_symbols.paste = 'Ã'
let g:airline_symbols.paste = 'âˆ¥'
let g:airline_symbols.spell = 'ê¨'
let g:airline_symbols.notexists = 'âˆ„'
let g:airline_symbols.whitespace = 'Î'

let g:airline_left_sep = 'î‚°'
let g:airline_left_alt_sep = 'î‚±'
let g:airline_right_sep = 'î‚²'
let g:airline_right_alt_sep = 'î‚³'
let g:airline_symbols.branch = 'î‚ '
let g:airline_symbols.readonly = 'î‚¢'
let g:airline_symbols.linenr = 'î‚¡'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  let g:airline_theme='hybrid'
'''

[[plugins]]
repo = 'w0ng/vim-hybrid'
# hook_add = '''
#   set background=dark
#   " lazy seting
#   if has('nvim')
#     autocmd MyAutoCmd VimEnter * nested colorscheme hybrid
#   endif
# '''

# [[plugins]]
# repo = 'edkolev/tmuxline.vim'

# [[plugins]]
# repo = 'Yggdroot/indentLine'
# on_path = '.*'
# hook_add = '''
#   let g:indentLine_enabled = 1
#   let g:indentLine_fileTypeExclude = ['help', 'json']
#   let g:indentLine_concealcursor = 'c'
#   let g:indentLine_conceallevel=1
# '''

##################################################################
# syntax

[[plugins]] # js syntax
repo = 'jelera/vim-javascript-syntax'
# repo = 'othree/yajs.vim'
# repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'kylef/apiblueprint.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
  let g:polyglot_disabled = ['javascript']
  " vim-cpp-enhanced-highlight
  let g:cpp_class_scope_highlight = 1
'''

# polyglot includes these
#
# repo = 'cespare/vim-toml'
# repo = 'rust-lang/rust.vim'
# repo = 'leafgarland/typescript-vim'
# repo = 'octol/vim-cpp-enhanced-highlight'

